[package]
name = "local_file_cache"
version = "0.1.3"
edition = "2021"
description = "Cache contents in local file."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.5"
dirs = "4.0.0"
